### PR TITLE
fix domain_migration for gluon v2018.2

### PR DESCRIPTION
**Pull request by krombel**
remove usage of nixio and use luaposix instead

### CODE REVIEW

**Comment by ponschab** [comment]
https://github.com/freifunkMUC/gluon-packages/blob/6831ac4c291e70894cb6d15678fb3130b4988f96/gluon-domain-migration-ffmuc/files/lib/gluon/upgrade/002-domain-migration#L41
`/usr/bin/lua: ./002-domain-migration:41: attempt to call field 'move' (a nil value)
stack traceback:
	./002-domain-migration:41: in main chunk
	[C]: ?
`

That must be "pio.rename(tmpsysfile, sysfile)" instead of "pio.move(tmpsysfile, sysfile)".

**Comment by krombel** [comment]
Thanks for testing it. I have incorporated your suggestion.
As you have tested it, I will then merge it

**Comment by ponschab** [comment]
Well, let's hope I'm not completely confused.

**Comment by krombel** [comment]
I tested it on my device and it seems /etc/sysupgrade.conf is not present anymore.
Therefore I added 8760bc5a12419bf66a7cf6aadea35eca0eb0a3fd. Now I am confident enough that is works

**Pull request merged**
